apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasl-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tasl-prod
  template:
    metadata:
      name: mypod1
      labels:
        name: tasl-prod
    spec:
      containers:
      - name: mycontainer
        image: muruganhub/tasl-prod:7
      imagePullSecret:
      - name: secretdocker
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    name: tasl-prod
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: secretdocker
type: kubernetes.io/basic-auth
stringData:
  username: muruganhub # required field for kubernetes.io/basic-auth
  password: Sureshraina@3 # required field for kubernetes.io/basic-auth

        
